### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by ikresoft** [skoczen/django-ajax-uploader#62]
When I try to upload it creates file on server with 0 bytes, in firebug result is all ok, What I did to resolve problem is I use mbraak fork and is working.

**Comment by skoczen** [comment]
Thanks for the issue - can you link to the fork that worked?

**Comment by ikresoft** [comment]
https://github.com/mbraak/django-ajax-uploader

**Comment by ikresoft** [comment]
Is there any improve on this issue?

**Comment by skoczen** [comment]
Not yet - the differences between that branch and this one are significant, there are licensing issues, and this isn't a top priority for me at the moment. (I think it's better to be honest than well-meaning in situations like this!)

A pull request that explained the rationale behind the changes other than "this fixes an obscure zero-byte-file bug" is probably what it would take to get this merged.

For clarity, we use ajaxuploader every day using the latest (licensed) fine uploader, and it works great.  Since that fork includes a newer fineuploader (GPL version), that could be the fix - perhaps give this branch a shot with the new, licensed version?

**Comment by skoczen** [comment]
Closing this, as the solution here (and as people have found in #64) is to use Fineuploader, with

``` js
forceMultipart: false,
paramsInBody: false
```
