### ISSUE TITLE
Additional model fields

### ISSUE THREAD

**Issue by howieweiner** [skoczen/django-ajax-uploader#63]
Hi

Great library. Worked first time. Just wondering if there is a way to add additional model fields to the upload form which can then be accessed via the signal. e.g. I have a file description and checkbox that need sending along with the file.

Thanks

**Comment by skoczen** [comment]
Hi there,

Thanks, glad to hear it! 

Custom fields - sort of. 

On the back-end, yes.  You'd could theoretically use a custom backend, and then add the additional functionality you require to the `upload_complete` handler, which has the full request object.  Front end's a bit more complicated, since this isn't designed to be a django form replacement.  You could extend fineuploader (or possibly use features on a newer version - I'm not completely up to date) to send your data.

In practice, if you're good with two requests, people handle handle situations like that by sending the form data separately. If you need them to be dependent, you can use the `onComplete` callback in the uploader.

Hope that helps!

**Comment by howieweiner** [comment]
Hi there

Thanks for the input. I did some reading up on fineuploader, and it turned out to be really easy. It is possible to embed the upload field in a form, and for all other form data to be passed as params - which are then available to the signal.

http://docs.fineuploader.com/features/forms.html

Not so easy with file-uploader, I guess. Fine uploader is great, but I'm still not clear on the GPL licence restrictions.

I guess two requests would be the other way to go

Thanks

**Comment by skoczen** [comment]
Closing this since it's working with fineuploader, and that's the recommended js library!
