### ISSUE TITLE
Loading an empty file

### ISSUE THREAD

**Issue by sweet-watermelon** [skoczen/django-ajax-uploader#64]
Hello.

If i use your 'fileuploader.js', files are loading correctly, but if i use latest version of fileuploader files are loaded empty (0 bytes).

I opened the debugger and saw that the new version of fileuploader sends request like this

```
  Content-Type:multipart/form-data;
```

How i can fix it?

**Comment by georgedorn** [comment]
I'm having the same issue, but only for local file uploads.

**Comment by georgedorn** [comment]
A temporary workaround appears to be setting forceMultipart to false and paramsInBody to false in the request section of the fineuploader config.  Otherwise, request.read() contains nothing and Django puts the file contents into request.FILES, even if is_ajax() is true.  A major reworking of ajaxupoader.views.base would be needed to detect this situation.

**Comment by derek-adair** [comment]
Probably close this as a duplicate.
